{
 "title": "Power Usage",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Power Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "l1_power_usage_value{job=\"power-reader\", unit=\"Watt\"}"
    }
   ]
  },
  {
   "title": "Current (Ampere)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "expr": "l1_amperage_value{job=\"power-reader\", unit=\"Ampere\"}"
    }
   ]
  },
  {
   "title": "Voltage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "expr": "l1_voltage_value{job=\"power-reader\", unit=\"Volt\"}"
    }
   ]
  },
  {
   "title": "Gas Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "m3" } },
   "targets": [
    {
     "expr": "gas_used_value{job=\"power-reader\", unit=\"CubicMeter\"}"
    }
   ]
  }
 ]
}